### ISSUE TITLE
Consider my RidgeHacks website

### ISSUE THREAD

**Issue by cdknight** [michaelwu21/RidgeHacks#1]
It is written in PHP and JS, but that can easily change.

It uses SQL as a backend, and is **much** more dynamic than what we have here. Also I'm sure we could use Bootstrap to get it to look how you want it.

**Comment by cdknight** [comment]
It would be more dynamic when actually doing the events, as well, to have a database of names. We could use this db for creating schedules/logistics.

**Comment by zhenguwu** [comment]
Lol I need to finish the basic info of the website first, currently just a template

**Comment by cdknight** [comment]
I already have a template. It has CSS and everything as well. My only things is I totally forgot the name of the event and used something else, and I can't edit it right now because I am in the process of getting a new PHPStorm subscription or switching to eclipse.

**Comment by cdknight** [comment]
See my website at

https://gitlab.com/cdknight/ridgehackswebsite.

You will need a full LAMP or LEMP or LLMP or WIMP or MAMP or MEMP or FAMP or FEMP or WAMP or WEMP stack to get this working. 

You'll need to get started by creating a new database and a new user in mysql.

The base css should work with just a PHP environment and no database.

**Comment by cdknight** [comment]
Yes, my website looks like trash. But, **using these bootstrap templates and whatnot**, l18n is better there **and** it is not static HTML, meaning it is easier to change stuff.

**Comment by cdknight** [comment]
This is a **large** selling point.
