### ISSUE TITLE
Fix text colors

### ISSUE THREAD

**Issue by cdknight** [michaelwu21/RidgeHacks#8]
![image](https://user-images.githubusercontent.com/25418058/47400321-ac96aa00-d70a-11e8-84bd-a1c2fbc3d516.png)

This grey-on-pink text is **not** acceptable and is **not** presentable.

**Comment by zhenguwu** [comment]
Oh Shrey fixed that in his pull request

**Comment by cdknight** [comment]
Please review my pull request
